apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim
  namespace: bomtada
  labels:
    app: claim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claim
  template:
    metadata:
      labels:
        app: claim
    spec:
      containers:
        - name: claim
          image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user10-claim:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: api.url.review
              valueFrom:
                configMapKeyRef:
                  name: bomtada-config
                  key: api.url.review
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: claim
  namespace: bomtada
  labels:
    app: claim
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: claim
