apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: bomtada
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user10-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: bomtada
  labels:
    app: consumer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: consumer
