apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: bomtada
  labels:
    app: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user10-history:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: history
  namespace: bomtada
  labels:
    app: history
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: history
